version: '3.9'

services:  
  shipment_db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipment_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - "./shipment_db.sql:/docker-entrypoint-initdb.d/1.sql"
    container_name: shipment_db
